# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tiger
      POSTGRES_USER: toni
      POSTGRES_DB: template
    ports:
      - 5433:5433

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432